### ISSUE TITLE
IO Board Firmware Sharing

### ISSUE THREAD

**Issue by jancona** [jimahlstrom/HL2IOBoard#1]
Hi,
I've been working on some firmware mods for my own use that might also be useful to others. Has you thought about the model for sharing firmware?

So far, I've cloned this repo, then copied and renamed n2adr_basic. All my changes are in my subdirectory, but I use functions from n2adr_lib. When I'm ready to share my firmware, I could:

* Send a pull request to this repo, which you could review and merge (or not).
* Just publish it to my fork and post info about it to the HL2 mailing list, wiki, etc.
* Something else?

Do you have any thoughts or preferences about this?

Thanks,

Jim
N1ADJ

**Comment by jimahlstrom** [comment]
Hello Jim,

I think you should have a subdirectory next to n2adr_basic for your code.
So a pull request seems best, although if our gits are different in other
places there may be a problem. I am not sure if I can pull just a single
directory. Or a zipfile with your directory works too.

Jim
N2ADR

**Comment by jancona** [comment]
I can control which files are in the pull request. My firmware is to control the Hardrock-50 amplifier, so I'll put all my changes in a directory named `n1adj_hr50`, if that sounds good to you.
 
I still have some cleanup to do, but I should have a PR put together soon.

Jim
N1ADJ

**Comment by TechMindsYT** [comment]
@jancona I would most definitely be interested in your FW for the HR50 as I have one on it's way to me now. Where is the best place to keep an eye out for your release? thanks, Matt M0DQW

**Comment by jancona** [comment]
@TechMindsYT When it's ready I will submit a pull request and when Jim N2ADR merges it it will show up in this repository.

**Comment by jimahlstrom** [comment]
I have a new Quisk version 4.2.27 for the antenna tuner. Please test.

Jim
N2ADR
